# Generated by Django 6.0.7 on 2026-08-05 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('bio', models.TextField(blank=True, verbose_name='Bio courte')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog/authors/', verbose_name='Photo')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('dribbble', models.URLField(blank=True, verbose_name='Dribbble')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Question (FAQ)',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name="Titre de l'étape")),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Étape du processus',
                'verbose_name_plural': 'Processus de travail',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-solid fa-check', help_text="Classe d'icône Font Awesome, ex: fa-solid fa-lightbulb, fa-solid fa-comments", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Qualité',
                'verbose_name_plural': 'Qualités (header À propos)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='Icône / image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('image_1', models.ImageField(blank=True, help_text='Petite photo au premier plan (bas-gauche de la galerie)', null=True, upload_to='services/approach/')),
                ('image_2', models.ImageField(blank=True, help_text='Grande photo en arrière-plan (haut-droite de la galerie)', null=True, upload_to='services/approach/')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_script', models.CharField(default='Nos Services', max_length=100, verbose_name='Titre manuscrit')),
                ('subtitle', models.CharField(blank=True, default='Ce que je peux faire pour vous', max_length=255, verbose_name='Sous-titre')),
                ('description', models.TextField(blank=True, default='', verbose_name="Texte d'introduction")),
            ],
            options={
                'verbose_name': 'Intro Services',
                'verbose_name_plural': 'Intro Services',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='technologies/icons/')),
                ('fallback_color', models.CharField(default='#A8536A', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('education', 'Parcours académique'), ('experience', 'Expérience professionnelle')], max_length=20)),
                ('year', models.CharField(help_text='Ex: 2022 — 2024', max_length=50)),
                ('title', models.CharField(help_text='Diplôme obtenu ou intitulé du poste', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text="École / université, ou nom de l'entreprise", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-solid fa-graduation-cap', help_text="Classe d'icône Font Awesome, ex: fa-solid fa-graduation-cap, fa-solid fa-briefcase", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = en premier, généralement du plus ancien au plus récent)")),
            ],
            options={
                'verbose_name': 'Entrée de parcours',
                'verbose_name_plural': 'Parcours & expérience',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.CharField(help_text='Affiché sur la carte de la liste des articles.', max_length=300, verbose_name='Extrait / description courte')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('featured_quote', models.CharField(blank=True, help_text='Ex : "Le design n\'est pas juste ce à quoi ça ressemble..."', max_length=300, verbose_name='Citation mise en avant')),
                ('featured_quote_author', models.CharField(blank=True, help_text='Ex : "Steve Jobs". Laisser vide si la citation est de toi.', max_length=100, verbose_name='Auteur de la citation')),
                ('image', models.ImageField(help_text='Utilisée dans la hero de la page de détail et la carte de la liste.', upload_to='blog/articles/', verbose_name='Image principale')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Temps de lecture (minutes)')),
                ('is_featured', models.BooleanField(default=False, help_text='Affiché dans le widget "Featured Post" de la sidebar.', verbose_name='Article à la une')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.author', verbose_name='Auteur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('short_description', models.CharField(help_text='Résumé affiché sur la carte et en haut de la page détail.', max_length=250)),
                ('description', models.TextField(help_text='Texte complet, section « About the Project ».')),
                ('status', models.CharField(choices=[('production', 'En production'), ('development', 'En développement'), ('prototype', 'Prototype')], default='development', max_length=20)),
                ('client', models.CharField(blank=True, help_text='Laisser vide si projet personnel.', max_length=100)),
                ('role', models.CharField(blank=True, help_text='Ex : "Full Stack Developer"', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='Ex : "3 Months"', max_length=50)),
                ('project_date', models.DateField(help_text="Sert à afficher le mois/année (carte) et l'année (détail).")),
                ('team_size', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour afficher « Projet personnel ».', null=True)),
                ('thumbnail', models.ImageField(help_text='Image affichée sur la carte, dans la grille.', upload_to='projects/thumbnails/')),
                ('hero_image', models.ImageField(blank=True, help_text='Grand visuel/mockup en haut de la page détail (optionnel, sinon thumbnail est réutilisée).', null=True, upload_to='projects/hero/')),
                ('live_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectcategory')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='core.technology')),
            ],
            options={
                'ordering': ['-project_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('problem', 'Problème'), ('solution', 'Solution')], max_length=10)),
                ('text', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='core.project')),
            ],
            options={
                'ordering': ['kind', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_suggestions', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/screenshots/')),
                ('caption', models.CharField(blank=True, help_text='Petit titre affiché sur la vignette, ex : "Lessons".', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex : "Active Users"', max_length=60)),
                ('value', models.CharField(help_text='Ex : "2K+", "85%", "4.9 / 5"', max_length=30)),
                ('icon', models.CharField(choices=[('users', 'Utilisateurs'), ('trending-up', 'Progression'), ('star', 'Note / étoile'), ('clock', 'Temps'), ('check', 'Validation')], default='check', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=80)),
                ('author_role', models.CharField(blank=True, max_length=80)),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='projects/testimonials/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'session_key')},
            },
        ),
    ]
