# Generated by Django 6.0.7 on 2026-08-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_article_likes_count_articlelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone'),
        ),
    ]
