# Generated by Django 6.0.7 on 2026-08-12 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_article_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.articlecomment')),
            ],
            options={
                'unique_together': {('comment', 'session_key')},
            },
        ),
    ]
