# Generated by Django 6.0.7 on 2026-08-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='article',
        ),
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'Like de commentaire', 'verbose_name_plural': 'Likes de commentaires'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('published', 'Publié'), ('hidden', 'Masqué'), ('spam', 'Spam')], default='published', max_length=20, verbose_name='Statut')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('replies_count', models.PositiveIntegerField(default=0, verbose_name='Réponses')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.comment'),
        ),
        migrations.CreateModel(
            name='ReportedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Contenu inapproprié'), ('harassment', 'Harcèlement'), ('other', 'Autre')], max_length=20, verbose_name='Motif')),
                ('session_key', models.CharField(max_length=40, verbose_name='Session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.comment')),
            ],
            options={
                'verbose_name': 'Commentaire signalé',
                'verbose_name_plural': 'Commentaires signalés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'status', '-created_date'], name='core_commen_article_f6776d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='core_commen_parent__e30d40_idx'),
        ),
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
