# Generated by Django 6.0.7 on 2026-08-14 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_author_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNotificationSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Notification d'article envoyée",
                'verbose_name_plural': "Notifications d'articles envoyées",
            },
        ),
        migrations.AlterModelOptions(
            name='articlesubscriber',
            options={'ordering': ['-created_at'], 'verbose_name': 'Abonné newsletter', 'verbose_name_plural': 'Abonnés newsletter'},
        ),
        migrations.RemoveField(
            model_name='articlesubscriber',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='articlesubscriber',
            name='subscribed_at',
        ),
        migrations.AddField(
            model_name='articlesubscriber',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='Token de confirmation'),
        ),
        migrations.AddField(
            model_name='articlesubscriber',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le'),
        ),
        migrations.AddField(
            model_name='articlesubscriber',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='articlesubscriber',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='articlesubscriber',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('unsubscribed', 'Désabonné')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='articlesubscriber',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration du token'),
        ),
        migrations.AddField(
            model_name='articlesubscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='Token de désabonnement'),
        ),
        migrations.AddField(
            model_name='comment',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core.articlesubscriber', verbose_name='Abonné'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['subscriber'], name='core_commen_subscri_9005ed_idx'),
        ),
        migrations.AddField(
            model_name='articlenotificationsent',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sent', to='core.article'),
        ),
    ]
