# Generated by Django 6.0.7 on 2026-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_newsletter_subscriber_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesubscriber',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
