"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xy-bwzr1@hvj(er3+nwcnik6wrkndg4_!6qclel8%fw*97jldx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

SITE_DOMAIN = 'http://127.0.0.1:8000'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'core',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =============================================================================
# EMAIL CONFIGURATION -django pour envoyer des emails via SMTP
# =============================================================================

import os

# 1. Quel service email utiliser (Gmail, SendGrid, Mailgun, etc.)
# 'smtp' = Simple Mail Transfer Protocol, le protocole standard
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2. Adresse du serveur SMTP de Gmail
# smtp.gmail.com = le serveur de Google
EMAIL_HOST = 'smtp.gmail.com'

# 3. Port de connexion
# 587 = port standard pour TLS (sécurité)
EMAIL_PORT = 587

# 4. Utiliser TLS pour chiffrer la connexion
# TLS = Transport Layer Security, chiffre les données pendant l'envoi
EMAIL_USE_TLS = True

# 5. Ton adresse email (remplace par la tienne)
# C'est l'adresse qui ENVOIE les messages
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')

# 6. Mot de passe d'application (PAS ton mot de passe normal)
# Comment obtenir un mot de passe d'application :
#    Google Account → Sécurité → Authentification à 2因素 → Mots de passe d'application
# IMPORTANT : stocke ceci dans .env, JAMAIS en dur dans le code !
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# 7. L'adresse qui apparaît comme expéditeur dans les emails
# Format : "Nom" <email@domaine.com>
DEFAULT_FROM_EMAIL = f'Estha Portfolio <{os.getenv("EMAIL_HOST_USER")}>'

# 8. Ton adresse email où tu reçois les messages
# Quand quelqu'un remplit le formulaire, c'est ICI que tu recois le mail
CONTACT_RECIPIENT_EMAIL = os.getenv('CONTACT_RECIPIENT_EMAIL')

# =============================================================================
# CKEDITOR 5 CONFIGURATION
# =============================================================================
SITE_ID = 1

CKEDITOR_5_FILE_UPLOAD_TO = 'ckeditor5/'
CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.DefaultStorage'

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': [
                'heading',
                '|',
                'bold', 'italic', 'underline', 'strikethrough', 'code', 'subscript', 'superscript', 'removeFormat',
                '|',
                'link', 'blockquote', 'codeBlock',
                '|',
                'bulletedList', 'numberedList', 'todoList',
                '|',
                'insertImage', 'insertTable', 'mediaEmbed',
                '|',
                'alignment',
                '|',
                'undo', 'redo',
            ],
            'shouldNotGroupWhenFull': True,
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraphe', 'class': 'ck-heading_paragraph'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Titre H2', 'class': 'ck-heading_h2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Titre H3', 'class': 'ck-heading_h3'},
            ]
        },
        'codeBlock': {
            'languages': [
                {'language': 'plain', 'label': 'Plain text'},
                {'language': 'python', 'label': 'Python'},
                {'language': 'django', 'label': 'Django'},
                {'language': 'html', 'label': 'HTML'},
                {'language': 'css', 'label': 'CSS'},
                {'language': 'javascript', 'label': 'JavaScript'},
                {'language': 'typescript', 'label': 'TypeScript'},
                {'language': 'sql', 'label': 'SQL'},
                {'language': 'json', 'label': 'JSON'},
                {'language': 'bash', 'label': 'Bash'},
                {'language': 'php', 'label': 'PHP'},
                {'language': 'java', 'label': 'Java'},
                {'language': 'c', 'label': 'C'},
                {'language': 'cpp', 'label': 'C++'},
                {'language': 'csharp', 'label': 'C#'},
                {'language': 'xml', 'label': 'XML'},
            ],
        },
        'image': {
            'styles': {
                'side': 'Float',
                'alignLeft': 'Left',
                'alignCenter': 'Centered image',
                'alignRight': 'Right',
            },
            'toolbar': [
                'imageTextAlternative',
                '|',
                'imageStyle:alignLeft',
                'imageStyle:alignCenter',
                'imageStyle:alignRight',
                '|',
                'imageStyle:side',
            ],
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties',
            ],
        },
        'link': {
            'defaultProtocol': 'https://',
        },
    }
}
